"use client";

import React, { useState, useEffect, useRef } from 'react';
import { FileText, FolderPlus, Star, Trash2, Download, Upload, Plus } from 'lucide-react';
import { getSavedFiles, toggleFavoriteInStore, moveToTrashInStore, saveFileToStore, StoredFile } from '../../../lib/dashboard-store';
import { downloadBlobFile } from '../../../lib/pdf-engine';

export default function UserFilesPage() {
  const [files, setFiles] = useState<StoredFile[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setFiles(getSavedFiles().filter(f => !f.isTrash));
  }, []);

  const handleToggleFav = (id: string) => {
    const updated = toggleFavoriteInStore(id);
    setFiles(updated.filter(f => !f.isTrash));
  };

  const handleDelete = (id: string) => {
    const updated = moveToTrashInStore(id);
    setFiles(updated.filter(f => !f.isTrash));
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const selected = Array.from(e.target.files);
      selected.forEach(file => {
        const stored: StoredFile = {
          id: Date.now().toString() + Math.random().toString(36).substring(2, 5),
          name: file.name,
          sizeBytes: file.size,
          sizeFormatted: `${(file.size / 1024 / 1024).toFixed(2)} MB`,
          tool: 'Uploaded PDF',
          date: new Date().toISOString().replace('T', ' ').substring(0, 16),
          isFav: false,
          isTrash: false,
          pages: 1
        };
        saveFileToStore(stored);
      });
      setFiles(getSavedFiles().filter(f => !f.isTrash));
    }
  };

  const handleDownload = (file: StoredFile) => {
    downloadBlobFile(
      `Sample PDF content payload for ${file.name}\nGenerated by PDFMaster Pro Engine by Suraj Vishwakarma.`,
      file.name,
      'application/pdf'
    );
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-900 dark:text-white">My PDF Documents</h1>
          <p className="text-xs text-slate-500">Manage, upload, favorite, and download your PDF files.</p>
        </div>
        <div className="flex items-center gap-3">
          <input
            type="file"
            ref={fileInputRef}
            onChange={handleFileUpload}
            multiple
            accept=".pdf,image/*"
            className="hidden"
          />
          <button
            onClick={() => fileInputRef.current?.click()}
            className="px-5 py-2.5 rounded-2xl bg-purple-600 hover:bg-purple-700 text-white font-extrabold text-xs shadow-md shadow-purple-500/20 flex items-center gap-2"
          >
            <Upload className="w-4 h-4" /> Upload Document
          </button>
        </div>
      </div>

      {/* File List Grid */}
      <div className="glass-card rounded-3xl p-6 border border-slate-200 dark:border-slate-800 space-y-4">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {files.map((file) => (
            <div key={file.id} className="p-4 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 space-y-3 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex items-center justify-between">
                <div className="p-2.5 rounded-xl bg-purple-100 dark:bg-purple-950 text-purple-600">
                  <FileText className="w-5 h-5" />
                </div>
                <button onClick={() => handleToggleFav(file.id)} className="text-slate-400 hover:text-amber-500">
                  <Star className={`w-4 h-4 ${file.isFav ? 'text-amber-500 fill-amber-500' : ''}`} />
                </button>
              </div>

              <div>
                <h4 className="text-xs font-bold text-slate-900 dark:text-white truncate">{file.name}</h4>
                <p className="text-[10px] text-slate-400 mt-0.5">{file.sizeFormatted} • {file.tool}</p>
              </div>

              <div className="pt-2 border-t border-slate-100 dark:border-slate-700/60 flex items-center justify-between text-xs">
                <span className="text-[10px] text-slate-400">{file.date}</span>
                <div className="flex items-center gap-2">
                  <button onClick={() => handleDownload(file)} className="p-1 text-slate-500 hover:text-purple-600" title="Download"><Download className="w-3.5 h-3.5" /></button>
                  <button onClick={() => handleDelete(file.id)} className="p-1 text-slate-500 hover:text-red-500" title="Delete"><Trash2 className="w-3.5 h-3.5" /></button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
