export interface PDFTool {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: 'organize' | 'optimize' | 'convert_to' | 'convert_from' | 'edit' | 'security' | 'intelligence';
  categoryChip: 'All' | 'Workflows' | 'Edit PDF' | 'PDF Security' | 'PDF Intelligence';
  icon: string;
  badge?: string;
  popular?: boolean;
}

export const PDF_TOOLS: PDFTool[] = [
  // Organize PDF
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    category: 'organize',
    categoryChip: 'Workflows',
    icon: 'Combine',
    popular: true,
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    category: 'organize',
    categoryChip: 'Workflows',
    icon: 'Split',
    popular: true,
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    title: 'Remove Pages',
    description: 'Delete unwanted pages from your document with custom range selections.',
    category: 'organize',
    categoryChip: 'Edit PDF',
    icon: 'Trash2',
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    title: 'Extract Pages',
    description: 'Extract specific pages from your PDF file and save them into a new document.',
    category: 'organize',
    categoryChip: 'Workflows',
    icon: 'FileOutput',
  },
  {
    id: 'organize-pdf',
    slug: 'organize-pdf',
    title: 'Organize PDF',
    description: 'Sort, delete, and reorder PDF pages visually using intuitive drag-and-drop.',
    category: 'organize',
    categoryChip: 'Workflows',
    icon: 'LayoutGrid',
  },
  {
    id: 'scan-pdf',
    slug: 'scan-pdf',
    title: 'Scan to PDF',
    description: 'Capture paper documents directly from mobile/webcam into high-clarity PDF.',
    category: 'organize',
    categoryChip: 'Workflows',
    icon: 'Scan',
  },

  // Optimize PDF
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF visual quality.',
    category: 'optimize',
    categoryChip: 'Workflows',
    icon: 'Minimize2',
    popular: true,
  },
  {
    id: 'repair-pdf',
    slug: 'repair-pdf',
    title: 'Repair PDF',
    description: 'Recover data from corrupted or damaged PDF documents instantly.',
    category: 'optimize',
    categoryChip: 'Workflows',
    icon: 'Wrench',
  },
  {
    id: 'ocr-pdf',
    slug: 'ocr-pdf',
    title: 'OCR PDF',
    description: 'Convert scanned PDF pages and images into searchable, selectable text.',
    category: 'optimize',
    categoryChip: 'PDF Intelligence',
    icon: 'Eye',
  },

  // Convert To PDF
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    title: 'JPG to PDF',
    description: 'Transform JPG, PNG, BMP, WEBP images to PDF in seconds with custom margins.',
    category: 'convert_to',
    categoryChip: 'Workflows',
    icon: 'Image',
    popular: true,
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    title: 'WORD to PDF',
    description: 'Make DOC and DOCX files easy to read by converting them to clean PDF.',
    category: 'convert_to',
    categoryChip: 'Workflows',
    icon: 'FileText',
    popular: true,
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    title: 'POWERPOINT to PDF',
    description: 'Turn your PPT and PPTX slideshows into clear, portable PDF slide decks.',
    category: 'convert_to',
    categoryChip: 'Workflows',
    icon: 'Presentation',
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    title: 'EXCEL to PDF',
    description: 'Make EXCEL spreadsheets easy to read and print by converting to PDF.',
    category: 'convert_to',
    categoryChip: 'Workflows',
    icon: 'Sheet',
  },
  {
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    title: 'HTML to PDF',
    description: 'Convert web pages or raw HTML code into pixel-perfect PDF documents.',
    category: 'convert_to',
    categoryChip: 'Workflows',
    icon: 'Code',
  },

  // Convert From PDF
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Extract all images contained in a PDF or convert each page to a separate JPG.',
    category: 'convert_from',
    categoryChip: 'Workflows',
    icon: 'FileImage',
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    title: 'PDF to WORD',
    description: 'Convert your PDF files into easy to edit DOC and DOCX documents with accuracy.',
    category: 'convert_from',
    categoryChip: 'Workflows',
    icon: 'FileCode',
    popular: true,
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    title: 'PDF to POWERPOINT',
    description: 'Turn your PDF files into editable PPT and PPTX presentation slideshows.',
    category: 'convert_from',
    categoryChip: 'Workflows',
    icon: 'Tv',
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    title: 'PDF to EXCEL',
    description: 'Pull data straight from PDFs into Microsoft Excel spreadsheets in seconds.',
    category: 'convert_from',
    categoryChip: 'Workflows',
    icon: 'Table',
  },

  // Edit PDF
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate individual or all pages in your PDF document effortlessly.',
    category: 'edit',
    categoryChip: 'Edit PDF',
    icon: 'RotateCw',
  },
  {
    id: 'add-page-numbers',
    slug: 'add-page-numbers',
    title: 'Add Page Numbers',
    description: 'Add page numbers to PDFs with custom typography, positioning and numbering format.',
    category: 'edit',
    categoryChip: 'Edit PDF',
    icon: 'Binary',
  },
  {
    id: 'add-watermark',
    slug: 'add-watermark',
    title: 'Add Watermark',
    description: 'Stamp an image or text over your PDF pages with transparency controls.',
    category: 'edit',
    categoryChip: 'Edit PDF',
    icon: 'Stamp',
  },
  {
    id: 'crop-pdf',
    slug: 'crop-pdf',
    title: 'Crop PDF',
    description: 'Crop margins and unwanted outer regions of your PDF pages visually.',
    category: 'edit',
    categoryChip: 'Edit PDF',
    icon: 'Crop',
  },

  // Security
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    title: 'Protect PDF',
    description: 'Encrypt your PDF with 256-bit AES passwords to restrict unauthorized access.',
    category: 'security',
    categoryChip: 'PDF Security',
    icon: 'Lock',
    popular: true,
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove password, security permissions, and encryption from protected PDFs.',
    category: 'security',
    categoryChip: 'PDF Security',
    icon: 'Unlock',
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    title: 'Sign PDF',
    description: 'Sign your document yourself or request digital signatures from collaborators.',
    category: 'security',
    categoryChip: 'PDF Security',
    icon: 'PenTool',
  },
  {
    id: 'redact-pdf',
    slug: 'redact-pdf',
    title: 'Redact PDF',
    description: 'Permanently blackout sensitive text, images and metadata from your PDF.',
    category: 'security',
    categoryChip: 'PDF Security',
    icon: 'Eraser',
  },
  {
    id: 'compare-pdf',
    slug: 'compare-pdf',
    title: 'Compare PDF',
    description: 'Side-by-side visual and text diff analyzer to highlight changes between PDFs.',
    category: 'security',
    categoryChip: 'PDF Security',
    icon: 'Columns',
  },

  // PDF Intelligence (AI)
  {
    id: 'ai-summarizer',
    slug: 'ai-summarizer',
    title: 'AI Summarizer',
    description: 'Summarize 100+ page contracts, papers and reports in seconds with Neural AI.',
    category: 'intelligence',
    categoryChip: 'PDF Intelligence',
    icon: 'Sparkles',
    badge: 'AI Powered',
    popular: true,
  },
  {
    id: 'translate-pdf',
    slug: 'translate-pdf',
    title: 'Translate PDF',
    description: 'Translate PDF document text into 50+ languages while preserving formatting.',
    category: 'intelligence',
    categoryChip: 'PDF Intelligence',
    icon: 'Languages',
    badge: 'AI Powered',
  },
  {
    id: 'ai-chat',
    slug: 'ai-chat',
    title: 'AI Chat with PDF',
    description: 'Ask questions, extract facts, and converse directly with your PDF documents.',
    category: 'intelligence',
    categoryChip: 'PDF Intelligence',
    icon: 'Bot',
    badge: 'AI Powered',
    popular: true,
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    title: 'PDF to Markdown',
    description: 'Convert PDFs to clean Github Flavored Markdown for LLMs and documentation.',
    category: 'intelligence',
    categoryChip: 'PDF Intelligence',
    icon: 'FileCode2',
  },
];
